### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by chahuistle** [qbicsoftware-archive/ncct-admin-portlet#9]
I am updating `.travis.yml` files across several portlets and I noticed that some files are missing. It seems as if this portlet was not created using the cookiecutters, but I might be wrong.

Are you having troubles with Travis? Can I assist you somehow?

**Comment by FriederikeHanssen** [comment]
It was created with cookie cutter. Will check on monday whther I accidentally missed pushing the files

**Comment by FriederikeHanssen** [comment]
Added the files
